.TH RTFM

.SH NAME

FMake \- "Fun" Make

.SH DESCRIPTION

FMake is a "funnnn" version of make written in the programming language go and designed
to maybe function on your system possibly. Check it out, it maybe works.

.SH SYNOPSIS

.B FMake
[options] [new <path>] [...]

.SH COMMANDS

.TP
.BR new " " <path>
Generate a new FMake project.

.SH OPTIONS

.TP
.BR \-h ", " \-\-help
Prints the FMake help message.

.TP
.BR \-S ", " \-\-Save
Save all of FMake's tmp files.

.TP
.BR \-v ", " \-\-version
Print version of FMake
